workerPoolSpecs:
- machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  pythonPackageSpec:
    executorImageUri: "us-docker.pkg.dev/vertex-ai/training/scikit-learn-cpu.0-23:latest"
    packageUris:
      - "gs://phase1gcp/code/src.tar"
    pythonModule: "src.train"
    args:
      - "--bucket"
      - "gs://phase1gcp"